# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: platform, action: index }

# platform
platforms:
  url:   /
  param: { module: platform, action: index }

platform_new:
  url:   /platform/create/
  param: { module: platform, action: new }

platform_check_cn:
  url:   /platform/check/*
  class: sfRequestRoute
  param: { module: platform, action: check }
  requirements:
    sf_method: [get]
    name: \w+

platform_edit:
  url:   /platform/edit/:platform
  param: { module: platform, action: edit }
  requirements:
    sf_method: [get]
    platform:

platform_status:
  url:   /platform/changestatus/:platform
  class: sfRequestRoute
  param: { module: platform, action: status }
  requirements:
    sf_method: [get]
    platform:

platform_delete:
  url:   /platform/destroy/:platform
  class: sfRequestRoute
  param: { module: platform, action: delete }
  requirements:
    sf_method: [get]
    platform:

# server
servers:
  url:   /server/:platform
  class: sfRequestRoute
  param: { module: server, action: index }
  requirements:
    sf_method: [get]
    platform:

server_new:
  url:   /server/create/:platform
  class: sfRequestRoute
  param: { module: server, action: new }
  requirements:
    sf_method: [get]
    platform:

server_status:
  url:   /server/changestatus/:platform/:server
  class: sfRequestRoute
  param: { module: server, action: status }
  requirements:
    sf_method: [get]
    platform:
    server:

server_edit:
  url:   /server/modify/:platform/:server
  class: sfRequestRoute
  param: { module: server, action: edit }
  requirements:
    sf_method: [get]
    platform:
    server:
 
server_delete:
  url:   /server/destroy/:platform/:server
  class: sfRequestRoute
  param: { module: server, action: delete }
  requirements:
    sf_method: [get]
    platform:
    server:

# company
companies:
  url:   /company/:platform
  class: sfRequestRoute
  param: { module: company, action: index }
  requirements:
    sf_method: [get]
    platform: \w+

company_new:
  url:   /company/add/
  param: { module: company, action: new }

company_edit:
  url:   /company/edit/
  param: { module: company, action: edit }

# domain
domains:
  url:   /domain/
  param: { module: domain, action: index }

domain_new:
  url:   /domain/add/
  param: { module: domain, action: new }

# user
users:
  url:   /user/
  param: { module: user, action: index }

user_new:
  url:   /user/add/
  param: { module: user, action: new }

user_edit:
  url:   /user/edit/
  param: { module: user, action: edit }

user_aliases:
  url:   /user/aliases/
  param: { module: user, action: aliases }

# group
groups:
  url:   /group/
  param: { module: group, action: index }

group_new:
  url:   /group/add/
  param: { module: group, action: new }

group_edit:
  url:   /group/edit/
  param: { module: group, action: edit }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

logout:
  url:   /:module/:action
  param: { module: security, action: logout }
