# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Zacacia
    description:  Zarafa Identity Manager
    keywords:     zarafa, identity
    #language:     en
    #robots:       index, follow

  stylesheets:    [zacacia.css, menu.css]

  javascripts:    [jquery/jquery.js, navigation.js]
#  javascripts:    [lib/jquery-1.7.min.js, lib/php.full.min-3.26.js, lib/jquery.tools.tooltip.min-1.2.6.js]
#  javascripts:    [lib/jquery-1.6.4.min.js, lib/jquery.tools.min-1.2.6.js, lib/php.full.min-3.26.js]

  has_layout:     true
  layout:         layout
