# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Zacacia
    description:  Zarafa Identity Manager
    keywords:     zarafa, identity
    viewport:     width=device-width, initial-scale=1.0
    #language:     en
    #robots:       index, follow

  stylesheets:    [zacacia.css]

  javascripts:    [bootstrap/bootstrap.js, jquery/jquery.js, phpjs/phpjs.js, navigation.js]

  has_layout:     true
  layout:         layout
