all:
    stylesheets:    [zacacia.css]

indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [indexServer.js]

newSuccess:
    stylesheets:    [form.css]
    javascripts:    [newServer.js, lib/jquery.observe_field.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [editServer.js]
