all:
    stylesheets:    [zacacia.css]

indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [server/index.js]

newSuccess:
    stylesheets:    [form.css]
    javascripts:    [server/new.js, jquery/jquery.observe_field.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [server/edit.js]
