indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [group/index.js]

newSuccess:
    stylesheets:    [form.css, zyaml.css]
    javascripts:    [group/lib.js, group/new.js, jquery/jquery.observe_field.js]

editSuccess:
    stylesheets:    [form.css, zyaml.css]
    javascripts:    [group/lib.js, group/edit.js, jquery/jquery.observe_field.js]
