zacacia_homepage:
    path:     /
    defaults: { _controller: ZacaciaBundle:Default:index }

zacacia_platform:
    path:   /platform
    defaults: { _controller: ZacaciaBundle:Platform:index }

zacacia_api_platform:
    path:   /api/:platform
    defaults: { _controller: ZacaciaBundle:Platform:getall, _format: json }
