general:
    # Optional: When using the LdapManager and there are multiple domains configured, the following domain
    #   will be selected first by default for any operations.
    default_domain: "zarafa.com"
    # Optional: The format that the schema is in. Default: yml
    schema_format: yml
    # Optional: The location to use when loading schema files. Default: "resources/schema" in the library
    #   root.
    schema_folder: "/var/www/src/ZacaciaBundle/Resources/schema"
    # The cache type to use. Either 'stash', 'doctrine', or 'none'. Default: none
    cache_type: doctrine
    # Optional: These are variable settings for the cache type in use.
    cache_options:
        # Type: stash, doctrine
        # Optional: The location to cache generated schema data. Default: The systems temporary directory.
        cache_folder: "/tmp/projectCache"
        # Type: stash
        # Optional: Whether the cache should auto-refresh based on mod times. This is enabled by default with stash.
        #  However, the doctrine type does not support it.
        cache_auto_refresh: false
domains:
    # At least one domain is required.
    zarafa:
        # Required: The full domain name.
        domain_name: "zarafa.com"
        # Required: The user to use for binding to LDAP and subsequent operations for the connection.
        username: admin
        # Required: The password for the user binding to LDAP.
        password: password
        # Recommended: The base DN (default naming context) for the domain. If this is empty then it will be queried
        #   from the RootDSE.
        base_dn: "ou=Zacacia,ou=Applications,dc=zarafa,dc=com"
        # Recommended: One or more LDAP servers to connect to. If this is empty then it will query DNS for a
        #   list of LDAP servers for the domain.
        servers: [ 'ldap' ]
        # Optional: The page size to use for paging operations, such as searches. Default: 1000
        page_size: 1000
        # Optional: The port to communicate to the LDAP servers on. If this is not set, the default is 389.
        #   If this is not set and 'use_ssl' is specified, the the port will be set to 636.
        port: 389
        # Optional: Whether or not to talk to LDAP over SSL. Default: false
        use_ssl: false
        # Optional: Whether or not to talk to LDAP over TLS. Default: false
        # If this is set to false, certain operations will not work. Such as password changes.
        use_tls: false
        # Optional: The LDAP type for this domain: ad, openldap. Default: ad
        ldap_type: openldap
        # Optional: Whether the connection should wait to bind until necessary (true) or bind immediately
        #   on construction (false). Default: false
        lazy_bind: false
        # Optional: When more than one server is listed for a domain, choose which one is selected for the
        #   connection. The possible choices are: order (tried in the order they appear), random. Default: order
        server_selection: order
        # Optional: The encoding type to use. Default: UTF-8
        encoding: UTF-8
        # Optional: The format that the username should be in when binding. This allows for two possible
        #   placeholders: %username% and %domainname%. The domain name parameter is the FQDN. Default: For AD
        #   the default is "%username%@%domainname%", for OpenLDAP it is simply "%username%". But you could easily
        #   make it something like "CN=%username%,OU=Users,DC=example,DC=local".
        #bind_format: "%username%"
        bind_format: "CN=%username%,DC=zarafa,DC=com"
        # schema_name: default ldap_type
        schema_name: zacacia
