all:
    stylesheets:    [zacacia.css]

indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [user/index.js]

newSuccess:
    stylesheets:    [form.css, zyaml.css]
    javascripts:    [user/lib.js, user/new.js, jquery/jquery.observe_field.js, jquery/jquery.pwdMeter.min.js, jquery/jquery.crypt.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [user/edit.js]

passwordSuccess:
    stylesheets:    [form.css]
    javascripts:    [user/password.js, jquery/jquery.observe_field.js, jquery/jquery.pwdMeter.min.js, jquery/jquery.crypt.js]
