all:
    stylesheets:    [zacacia.css]

indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [indexUser.js]

newSuccess:
    stylesheets:    [form.css]
    javascripts:    [newUser.js, jquery/jquery.observe_field.js, jquery/jquery.pwdMeter.min.js, jquery/jquery.crypt.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [editUser.js]

passwordSuccess:
    stylesheets:    [form.css]
    javascripts:    [passwordUser.js, jquery/jquery.observe_field.js, jquery/jquery.pwdMeter.min.js, jquery/jquery.crypt.js]
