indexSuccess:
    stylesheets:    [collection.css, tooltip.css]
    javascripts:    [indexUser.js]

newSuccess:
    stylesheets:    [form.css, input.css, button.css, tooltip.css, validator.css, password.css]
    javascripts:    [newUser.js, lib/jquery.observe_field.js, lib/jquery.pwdMeter.min-1.0.1.js, lib/jquery.crypt-1.1.0.js]

editSuccess:
    stylesheets:    [form.css, input.css, button.css, tooltip.css, validator.css]
    javascripts:    [editUser.js, lib/jquery.observe_field.js]

passwordSuccess:
    stylesheets:    [form.css, input.css, button.css, tooltip.css, validator.css, password.css]
    javascripts:    [passwordUser.js, lib/jquery.observe_field.js, lib/jquery.pwdMeter.min-1.0.1.js, lib/jquery.crypt-1.1.0.js]
