all:
    stylesheets:    [zacacia.css]

indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [company/index.js]

newSuccess:
    stylesheets:    [form.css]
    javascripts:    [company/new.js, jquery/jquery.observe_field.js, jquery/jquery.tools.validator.min.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [company/edit.js]
