indexSuccess:
    stylesheets:    [collection.css, tooltip.css]
    javascripts:    [indexCompany.js]

newSuccess:
    stylesheets:    [form.css, input.css, button.css, tooltip.css, validator.css]
    javascripts:    [newCompany.js, lib/jquery.observe_field.js]

editSuccess:
    stylesheets:    [form.css, input.css, button.css, tooltip.css, validator.css]
    javascripts:    [editCompany.js]
