all:
    stylesheets:    [zacacia.css]

indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [indexCompany.js]

newSuccess:
    stylesheets:    [form.css]
    javascripts:    [newCompany.js, lib/jquery.observe_field.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [editCompany.js]
