all:
    stylesheets:    [zacacia.css]

indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [indexCompany.js]

newSuccess:
    stylesheets:    [form.css]
    javascripts:    [newCompany.js, jquery/jquery.observe_field.js, jquery/jquery.tools.validator.min.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [editCompany.js]
