indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [domain/index.js]

newSuccess:
    stylesheets:    [form.css]
    javascripts:    [domain/new.js, jquery/jquery.observe_field.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [domain/edit.js]
