indexSuccess:
    stylesheets:    [collection.css, tooltip.css]
    javascripts:    [indexDomain.js]

newSuccess:
    stylesheets:    [form.css, button.css, tooltip.css, validator.css]
    javascripts:    [newDomain.js, jquery.observe_field.js]
