all:
    stylesheets:    [zacacia.css]

indexSuccess:
    stylesheets:    [collection.css]
    javascripts:    [indexDomain.js]

newSuccess:
    stylesheets:    [form.css]
    javascripts:    [newDomain.js, jquery/jquery.observe_field.js]

editSuccess:
    stylesheets:    [form.css]
    javascripts:    [editDomain.js]
