<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/01/12 23:17:48
return array(

  // sfProtoculousPlugin_module_libs

  // sfProtoculousPlugin_lib

  // project
  'platformpeer' => '/opt/WebSites/MinivISP/lib/ldap/PlatformPeer.php',
  'ldapcriteria' => '/opt/WebSites/MinivISP/lib/ldap/criteria/LDAPCriteria.class.php',
  'ldapobject' => '/opt/WebSites/MinivISP/lib/ldap/object/LDAPObject.class.php',
  'platformobject' => '/opt/WebSites/MinivISP/lib/ldap/object/PlatformObject.php',
  'baseplatformpeer' => '/opt/WebSites/MinivISP/lib/ldap/base/BasePlatformPeer.class.php',
  'baseldapeer' => '/opt/WebSites/MinivISP/lib/ldap/base/BaseLDAPeer.class.php',
  'sfwidgetformschemaformatterminivisp' => '/opt/WebSites/MinivISP/lib/sfWidgetFormSchemaFormatterMinivISP.class.php',
  'baseform' => '/opt/WebSites/MinivISP/lib/form/BaseForm.class.php',
  'minivispform' => '/opt/WebSites/MinivISP/lib/form/MinivISPForm.class.php',
  'platformnavigationform' => '/opt/WebSites/MinivISP/lib/form/PlatformNavigationForm.class.php',
  'platformform' => '/opt/WebSites/MinivISP/lib/form/PlatformForm.class.php',

  // project_model

  // application
  'myuser' => '/opt/WebSites/MinivISP/apps/admin/lib/myUser.class.php',

  // modules
);
